# File: .github/workflows/build-and-deploy.yml

name: Build and Deploy Java Application with Docker

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adoptium'  # Use the Adoptium distribution for JDK 8
          cache: 'maven'  # Optionally cache Maven dependencies

      - name: Install dependencies and build with Maven
        run: |
          mvn clean install  # Maven build command

      - name: Build Docker image
        run: |
          docker build -t my-java-app .  # Build Docker image using Dockerfile

      - name: Run Docker container (Test)
        run: |
          docker run --name my-java-container -d my-java-app
          docker logs my-java-container  # Show logs to verify the output

      - name: Push Docker image to Docker Hub (optional)
        if: github.ref == 'refs/heads/main'  # Only push when on main branch
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag my-java-app ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
